//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misa.Web08.TCDN.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misa.Web08.TCDN.API.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete employee failed.
        /// </summary>
        public static string DevMsg_Delete_Failed {
            get {
                return ResourceManager.GetString("DevMsg_Delete_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete employee success.
        /// </summary>
        public static string DevMsg_Delete_Success {
            get {
                return ResourceManager.GetString("DevMsg_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors occurred.
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get detail employee failed.
        /// </summary>
        public static string DevMsg_Get_Employee_Failed {
            get {
                return ResourceManager.GetString("DevMsg_Get_Employee_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter value passed in the procedure employee filter is wrong.
        /// </summary>
        public static string DevMsg_Get_Employee_Filter {
            get {
                return ResourceManager.GetString("DevMsg_Get_Employee_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code duplicate in database.
        /// </summary>
        public static string DevMsg_Insert_Duplicate {
            get {
                return ResourceManager.GetString("DevMsg_Insert_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert employee failed.
        /// </summary>
        public static string DevMsg_Insert_Failed {
            get {
                return ResourceManager.GetString("DevMsg_Insert_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert employee success.
        /// </summary>
        public static string DevMsg_Insert_Success {
            get {
                return ResourceManager.GetString("DevMsg_Insert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update employee failed.
        /// </summary>
        public static string DevMsg_Update_Failed {
            get {
                return ResourceManager.GetString("DevMsg_Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update employee success.
        /// </summary>
        public static string DevMsg_Update_Success {
            get {
                return ResourceManager.GetString("DevMsg_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occurred.
        /// </summary>
        public static string DevMsg_Validate_Failed {
            get {
                return ResourceManager.GetString("DevMsg_Validate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.amis.vn/api/v1/employees/delete.
        /// </summary>
        public static string MoreInfo_Delete_Failed {
            get {
                return ResourceManager.GetString("MoreInfo_Delete_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.amis.vn/api/v1/employees.
        /// </summary>
        public static string MoreInfo_Exception {
            get {
                return ResourceManager.GetString("MoreInfo_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân viên thất bại.
        /// </summary>
        public static string UserMsg_Delete_Failed {
            get {
                return ResourceManager.GetString("UserMsg_Delete_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân viên thành công.
        /// </summary>
        public static string UserMsg_Delete_Success {
            get {
                return ResourceManager.GetString("UserMsg_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra vui lòng liên hệ nhà phát triển.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy ra thông tin nhân viên thất bại.
        /// </summary>
        public static string UserMsg_Get_Employee_Failed {
            get {
                return ResourceManager.GetString("UserMsg_Get_Employee_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhân viên.
        /// </summary>
        public static string UserMsg_Get_Employee_Filter {
            get {
                return ResourceManager.GetString("UserMsg_Get_Employee_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại.
        /// </summary>
        public static string UserMsg_Insert_Duplicate {
            get {
                return ResourceManager.GetString("UserMsg_Insert_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhân viên thất bại.
        /// </summary>
        public static string UserMsg_Insert_Failed {
            get {
                return ResourceManager.GetString("UserMsg_Insert_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhân viên thành công.
        /// </summary>
        public static string UserMsg_Insert_Success {
            get {
                return ResourceManager.GetString("UserMsg_Insert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu phù hợp trả về.
        /// </summary>
        public static string UserMsg_Not_Found {
            get {
                return ResourceManager.GetString("UserMsg_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhân viên thất bại.
        /// </summary>
        public static string UserMsg_Update_Failed {
            get {
                return ResourceManager.GetString("UserMsg_Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhân viên thành công.
        /// </summary>
        public static string UserMsg_Update_Success {
            get {
                return ResourceManager.GetString("UserMsg_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string UserMsg_Validate_Failed {
            get {
                return ResourceManager.GetString("UserMsg_Validate_Failed", resourceCulture);
            }
        }
    }
}
